server:
  port: 16115

spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller

user-service:
  url: http://${USER_SERVICE_HOST:ts-user-service}:${USER_SERVICE_PORT:12342}