server:
  port: 18808

spring:
  application:
    name: ts-delivery-service
  datasource:
    url: jdbc:mysql://ts-delivery-mysql:3306/ts-delivery-mysql?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
  jpa:
    hibernate:
      ddl-auto: update
