server:
  port: 18673

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:10.176.122.77}
  application:
    name: ts-inside-payment-service

  data:
    mongodb:
      host: ts-inside-payment-mongo
#     username: user
#     password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: inside_payment.controller

order-service:
  url: http://${ORDER_SERVICE_HOST:ts-order-service}:${ORDER_SERVICE_PORT:12031}

order-other-service:
  url: http://${ORDER_OTHER_SERVICE_HOST:ts-order-other-service}:${ORDER_OTHER_SERVICE_PORT:12032}

payment-service:
  url: http://${PAYMENT_SERVICE_HOST:ts-payment-service}:${PAYMENT_SERVICE_PORT:19001}